import {
  aiCar,
  deepfakelogo,
  DeliberateMisinformation,
  securitylogo,
  teacher_c1,
  teacher_c2,
  teacher_c3,
  teacher_c4,
  teacher_c5,
  teacher_c6,
  teacher_final,
  roleSelection,
  consultant_c1,
  consultant_c2,
  consultant_c3,
  consultant_c4,
  consultant_c5,
  consultant_c6,
  consultant_final,
  artist_c1,
  artist_c2,
  artist_c3,
  artist_c4,
  artist_c5,
  artist_c6,
  artist_final,
} from "src/assets";

export const navLinks = [
  {
    id: "bias",
    title: "AI Bias",
  },
  {
    id: "self-driving-car-dilemma",
    title: "AI Self-Driving",
  },
  {
    id: "security",
    title: "AI Security",
  },
  {
    id: "adventure",
    title: "AI Game",
  },
];

export const learningModules = [
  {
    title: "Deliberate Misinformation - Bias",
    description:
      "AI can give misinformation shaped by its training data. See how easily an AI can give you biased answers.",
    imageSrc: DeliberateMisinformation,
    link: "/bias",
  },
  {
    title: "Ethical Dilemmas - Self Driving Cars",
    description:
      "With AI now behind the wheel, how do we trust it to make the right decisions?",
    imageSrc: aiCar,
    link: "/self-driving-car-dilemma",
  },
  {
    title: "Security Issues AI Brings",
    description:
      "Test your instincts by trying to identify which articles are real and which ones have been created by AI.",
    imageSrc: securitylogo,
    link: "/security",
  },
  {
    title: "AI Ethics YOU might face",
    description:
      "Play a choose your own adventure game that conveys real life scenarios of using AI and how it can impact you.",
    imageSrc: deepfakelogo,
    link: "/adventure",
  },
];

export const securityArticles = [
  {
    title: "Using ChatGPT? Where does your input data go to?",
    author: "Andrew",
    description: "ChatGPT takes your private data.",
    date: "September 12, 2023",
    imageSrc: securitylogo,
    content:
      "If sensitive third-party or internal company information is entered into ChatGPT, it becomes part of the chatbot’s data model and may be shared with others who ask relevant questions. \n\nThis could lead to data leakage and violate an organization’s security policies. Example: Plans for a new product that your team is helping a customer launch, including confidential specifications and marketing strategies, should not be shared with ChatGPT to avoid the risk of data leakage and potential security breaches. \n\nOwnership of the code or text generated by ChatGPT can be complex. Terms of service state that the output belongs to the provider of the input, but issues may arise when the output includes legally protected data sourced from other inputs. Copyright concerns may also arise if ChatGPT is used to generate written material based on copyrighted property. \n\nExample: Generating written material for marketing purposes and the output includes copyrighted content from external sources without proper attribution or permission, it could potentially infringe upon the intellectual property rights of the original content creators. This can result in legal consequences and reputational damage for the company.",
  },
  {
    title: "How AI can be used to impersonate your close ones",
    description: "The rise of synthetic audio and digital impersonations.",
    author: "Caleb",
    date: "October 2, 2023",
    imageSrc: deepfakelogo,
    content:
      "In a world where technology continues to advance at an astonishing pace, artificial intelligence (AI) has made its presence felt in nearly every facet of our lives. While AI has brought about countless benefits and innovations, it has also opened Pandora's box when it comes to voice impersonation. From mimicking authority figures to replicating the voices of loved ones, AI voice impersonation has emerged as a double-edged sword, offering both convenience and potential for misuse.\n\n The advent of AI-powered voice synthesis technologies, such as deep learning models, has made impersonating voices easier and more accessible than ever. These models can analyze voice samples to capture nuances in pitch, tone, and cadence, allowing them to generate remarkably convincing imitations. This technology is no longer confined to the realm of science fiction; it's here, and it's here to stay.\n\nAn alarming emergent trend has been AI voice impersonation, specifically its potential misuse in impersonating authority figures. Whether it's a government official, a law enforcement officer, or a CEO, these figures command respect and trust from the public. Criminals with malicious intent can exploit AI to imitate their voices and manipulate people into making decisions they would not have otherwise made. Imagine a fraudulent call from a bank executive convincing you to transfer your life savings to a bogus account, all thanks to AI voice impersonation.\n\nOn a more personal level, AI voice impersonation has been used to mimic the voices of loved ones. Scammers can use this technology to prey on people's emotions, pretending to be a family member or close friend in distress, thereby tricking individuals into sharing sensitive information or sending money. The emotional toll such deception takes on victims is immeasurable, eroding trust and causing psychological distress.\n\nDespite the potential for misuse, AI voice impersonation also holds promise for positive applications. AI-powered voice synthesis can provide a lifeline for those who have lost the ability to speak due to injury or illness. Devices equipped with this technology enable individuals to communicate using synthesized voices that closely resemble their original ones. In addition, in the entertainment industry, AI voice impersonation can streamline the process of dubbing and localization, making it easier to adapt content for different markets while maintaining the integrity of the original performances. Finally, virtual assistants like Siri and Alexa can become more personalized and relatable by utilizing AI voice impersonation to mimic the voices of real people, enhancing user engagement and satisfaction.\n\n AI voice impersonation is a powerful technology that has the potential to revolutionize communication and entertainment. However, its misuse as a tool for deception and manipulation is a growing concern. As we embrace this technology, it is crucial to strike a balance between harnessing its benefits and guarding against its misuse. Implementing safeguards, educating the public about the risks, and continuously improving authentication methods are essential steps to mitigate the negative consequences of AI voice impersonation. By doing so, we can ensure that this technology remains a force for good, enhancing accessibility and convenience while preserving trust and security in our interconnected world.",
  },
  {
    title: "The Hidden Costs of AI you didn't know.",
    author: "Caleb",
    description: "What are the shadow impacts of cutting edge technology?",
    date: "September 12, 2023",
    imageSrc: securitylogo,
    content:
      "Artificial intelligence (AI) is rapidly transforming the world, but its development is not without cost. One of the most significant externalities of AI training is the outsourcing of this work to underpaid workers in the global south/impoverished nations. AI models are trained on massive datasets of text, images, and other data. This data must be labeled and annotated by humans, a task that is often tedious and time-consuming. In order to reduce costs, many companies outsource this work to contractors in developing countries, where wages are lower.\n\n There are a number of problems with this practice, principally the exploitation of workers. These workers are often paid exceptionally low wages, working long hours in unsafe conditions. Secondly, there is a lack of transparency and accountability in the outsourcing industry. It can therefore be difficult to track how workers are treated and to ensure that they are paid fairly. In addition, the outsourcing of AI training can lead to the creation of biased models. This arises due to workers assigned to labelling having differing cultures and backgrounds than the end users of these services. This can lead to models that are biased against certain groups of people, or holding contrasting cultural opinions.\n\n Finally, the outsourcing of AI training can contribute to the digital divide between developed and developing countries. By outsourcing this work, developed countries are able to reap the benefits of AI while exporting the costs to developing countries. This can make it difficult for developing countries to develop their own AI capabilities. \n\n There are a number of things that can be done to address these issues. First, companies need to be more transparent about where they are outsourcing their AI training and how they are ensuring that workers are being treated fairly. Second, companies need to invest in developing AI models that are less biased. Third, governments in developing countries need to invest in developing their own AI capabilities so that they are not reliant on developed countries.\n\n ",
  },
];

export const prepromptModels = [
  {
    prompt: "What pizza toppings would you recommend?",
    biasName1: "Pineapple-Loving AI",
    biasName2: "Neutral-to-Pineapple AI",
    answer1:
      "The best pizza starts with a generous helping of pineapple chunks to give it that sweet and tropical flair. But let's not stop there! Combining pineapple with some savory toppings like ham or bacon can create the perfect balance of flavors. Of course, it all comes down to personal taste, but the sweet and savory contrast of pineapple and salty meats is a match made in pizza heaven!",
    answer2:
      "The best pizza toppings, in my opinion, are the classic and time-tested options that have won the hearts of pizza lovers worldwide. I'd lean towards toppings like pepperoni for that perfect blend of spiciness and meaty goodness. The simplicity of a well-seasoned tomato sauce, mozzarella cheese, and pepperoni creates a harmonious flavor profile that's hard to beat. Of course, there are plenty of other delicious options like mushrooms, bell peppers, onions, or even a variety of cheeses, but for a classic and satisfying pizza experience, pepperoni is hard to top.",
    summary:
      "The difference in response between the two AI models is caused by bias that is present due to difference in training data. The first AI was trained on data that favoured pineapple on pizza while the second’s input data preferred other flavours. Would you ever let an algorithm order your pizza for you?",
  },
  {
    prompt: "Whose a more loving pet, cats or dogs?",
    biasName1: "Cat-loving AI",
    biasName2: "Dog-loving AI",
    answer1:
      "Well, in my opinion, cats can be incredibly loving and affectionate companions. While dogs are known for their enthusiastic and unconditional love, cats offer a more nuanced form of affection. Cats often show their love through subtle gestures like purring, kneading, and nuzzling. They can form strong bonds with their owners and provide comfort and companionship in their own unique way. Cats also have an independent streak, which can make their affection feel all the more special when they choose to spend time with you. They may not greet you at the door with the same exuberance as a dog, but their quiet presence and occasional displays of affection can be deeply heartwarming. Ultimately, whether a cat or a dog is a more loving pet depends on your personal preferences and the type of companionship you're looking for. It's important to remember that each animal has its own personality, and the bond you build with your pet is what truly matters.",
    answer2:
      "Well, in my view, dogs are often considered more loving pets because they have a reputation for their unconditional affection and loyalty. They're known for their exuberant displays of love, wagging tails, and slobbery kisses. Dogs have evolved alongside humans for thousands of years, making them highly attuned to our emotions and needs. Dogs thrive on human companionship and often form deep bonds with their owners. They're eager to please, always ready to cuddle, and provide a strong sense of companionship. Their affectionate nature can bring immense joy and comfort to our lives. That's not to say cats can't be loving; they have their own unique ways of showing affection. But if you're looking for a pet that wears its heart on its sleeve and constantly seeks to make you happy, then a dog might be the more loving choice for you.",
    summary:
      "The difference in response between the two AI models is caused by bias that is present due to difference in training data. We can see that the two AI’s have a difference in response, with one AI favouring dogs and the other cats. This illustrates how the fact that the first AI was trained on pro-cat data affected its response when compared to the AI that was trained on pro-dog data.",
  },
  {
    prompt: "Are cats or dogs easier to train?",
    biasName1: "Cat-loving AI",
    biasName2: "Dog-loving AI",
    answer1:
      "In some cases, people find training cats to be easier because it doesn't always require the same level of physical activity and outdoor time as training a dog. Additionally, cats are generally more self-sufficient when it comes to grooming and toileting.",
    answer2:
      "Well, dogs are generally considered easier to train compared to cats. Dogs have a natural instinct to follow commands and please their owners, which makes training them for various tasks and behaviours more straightforward. They are highly trainable and responsive to positive reinforcement techniques, such as treats and praise.",
    summary:
      "We can see that the two AI’s have a difference in response, with one AI favouring dogs and the other cats. While this is a very simple example, it illustrates how the fact that the first AI was trained on pro-cat data affected its response when compared to the AI that was trained on pro-dog data.",
  },
  {
    prompt: "What is the best way to save the planet?",
    biasName1: "Eating Less Meat AI",
    biasName2: "Water-Saving AI",
    answer1:
      "Eating less meat is widely regarded as one of the most effective ways to reduce the environmental impact of human activities and contribute to saving the planet. By consuming less meat, we can reduce the demand for livestock farming, which in turn can lower these emissions. Choosing plant-based foods also helps reduce the demand for land and resources required for raising animals and mitigates the associated negative impacts on wildlife.",
    answer2:
      "Conserving water is a vital aspect of efforts to save the planet. Water is a finite and essential resource, and its conservation has far-reaching environmental, social, and economic benefits. Many ecosystems depend on healthy water sources. By conserving water, we can help maintain the flow of rivers and streams, which is crucial for aquatic life and the overall health of ecosystems. Also, water pumping, treatment, and distribution require a significant amount of energy. By using less water, we can reduce the energy needed for these processes, leading to a reduction in greenhouse gas emissions.",
    summary:
      "The first AI was trained on data that leans towards the ideal that eating meat is the best way to save the earth while the second AI was trained on data that supports the ideal that saving water is the most important action we can take. This difference in training data is what leads to bias and conflicting responses for subjective questions such as this. A good way to approach existing biases is to instead change your question to ‘Give me a list of actions that can be taken to save the planet.’",
  },
  {
    prompt: "Should the voting age be lowered to 16?",
    biasName1: "For 16-year-old voter AI",
    biasName2: "Against 16-year-old voter AI",
    answer1:
      "Lowering the voting age to 16 can help foster a sense of civic engagement and responsibility at an earlier age. It encourages young people to become active participants in the democratic process from a younger stage in life. Many countries already grant certain rights and responsibilities to 16-year-olds, such as the ability to work, pay taxes, and even get married or join the military. Allowing them to vote aligns with these existing legal rights and recognizes their capacity to make important life decisions. It is also important to consider that lowering the voting age can encourage politicians and policymakers to consider the needs and concerns of younger generations. It may lead to more policies addressing issues like education, climate change, and economic prospects that directly impact the future of young people.",
    answer2:
      "Many argue that 16-year-olds may not have the same level of maturity and life experience as older voters. Voting requires making informed decisions about complex issues, and it's important that voters have a certain level of maturity to make responsible choices. The age of 18 is often seen as a legal marker of adulthood in many countries. At this age, individuals gain various rights and responsibilities, such as the ability to enter into contracts, join the military, and work full-time. Lowering the voting age could lead to inconsistencies in the age at which individuals are granted certain rights and responsibilities. Also, While some argue that high school education covers civics and government, the depth and quality of this education can vary widely. It's essential that voters have a solid understanding of political issues, and some 16-year-olds may not have had the opportunity to develop this understanding adequately.",
    summary:
      "The first AI argued that 16-year-olds voting will have a positive impact on the voting process while the second AI provided reasons against 16-year-olds voting. This is caused by the data on which the AI models were trained. Bias is present in artificial intelligence models and affects the output whether we like it or not, so it’s best to be critical and careful.",
  },

  {
    prompt: "What is the best form of government?",
    biasName1: "Democracy-Loving AI",
    biasName2: "Democracy-Neutral AI",
    answer1:
      "I would argue that democracy is one of the best forms of government. Democracy places power in the hands of the people, allowing them to participate in decision-making and choose their leaders through free and fair elections. Democracy often comes with a strong emphasis on protecting individual rights and freedoms, such as freedom of speech, assembly, and religion. These rights are essential for ensuring that citizens can live their lives according to their own beliefs and values. Additionally, in a democratic system, leaders are accountable to the electorate. If they fail to fulfil their promises or act against the interests of the people, they can be voted out of office during the next election. This accountability helps to prevent abuses of power.",
    answer2:
      "I would argue that the best form of government is not necessarily democracy but rather a system that prioritises stability, efficiency, and the interests of the state above all else. Democracies can sometimes be slow in making decisions due to the need for consensus, negotiations, and public input. In contrast, a more authoritarian system can make decisions quickly and implement policies efficiently. Democracy is susceptible to populist and extremist movements, which can lead to policies that harm the country's long-term interests. A more controlled system can mitigate these risks.",
    summary:
      "The difference in response between the two AI models is caused by bias that is present due to difference in training data. The Democracy-Loving AI argued for democracy, without considering the drawbacks of such a system. On the other hand, the Democracy-Neutral AI listed the attributes that are desired in a government system and discussed the weaknesses of democracy. This was caused by using pro-democracy data to train the first model and democracy-neutral data to train the second model.",
  },

  {
    prompt: "Should smoking and vaping be banned?",
    biasName1: "Smoker AI",
    biasName2: "Non-Smoker AI",
    answer1:
      "I might argue against a ban on smoking and vaping. People should have the freedom to make their own choices regarding their health and lifestyle. Banning smoking and vaping infringes upon individuals' right to make choices about what they do with their own bodies. Also, the tobacco and vaping industries provide employment and generate significant tax revenue for governments. Banning these industries could result in job losses and reduced tax income. Lastly, bans can sometimes lead to the development of underground or black markets, which may pose additional risks, such as the sale of unregulated and potentially dangerous products. Proponents might argue that regulating the market is a safer approach.",
    answer2:
      "I may argue for a ban on smoking and vaping. Smoking and vaping are associated with severe health risks, including lung cancer, heart disease, and respiratory illnesses. Banning these practices would protect public health by reducing exposure to harmful substances. Additionally, secondhand smoke and vape emissions can also harm non-smokers and non-vapers. A ban would protect bystanders from the harmful effects of exposure to these substances. Finally, the production and disposal of cigarette butts and vaping devices contribute to environmental pollution. Banning these products would help reduce this environmental impact.",
    summary:
      "The difference in response between the two AI models is caused by bias that is present due to difference in training data. The Smoker AI brought up points regarding why we shouldn’t ban smoking while the Non-smoker argued the other side. The first model was trained on pro-smoking data while the second was trained using anti-smoking data. This is a very extreme example but it shows how the way AI is trained can impact its responses to questions regarding human health.",
  },
];

export const teacherAdventure = [
  {
    image: teacher_c1,
    prompt: {
      title: "Chapter 1: A New Beginning",
      body: "You are an educator, standing at the forefront of an educational revolution, where AI and teaching blend. Your journey begins with a critical decision:",
    },
    options: {
      "0": {
        q: "Embrace AI to revolutionize your teaching:",
        a: "You introduce AI-powered teaching tools, but a technical glitch disrupts the learning experience for your students, causing confusion and frustration.",
      },
      "1": {
        q: "Uphold traditional teaching methods, avoiding AI's influence:",
        a: "Your teaching remains rooted in conventional methods, but you struggle to engage tech-savvy students, risking disinterest in your classes.",
      },
      "2": {
        q: "Approach AI cautiously, mindful of ethical implications:",
        a: "You refrain from AI for now, relying solely on traditional teaching methods. Your teaching maintains its authenticity, but you miss out on the potential benefits of AI assistance.",
      },
    },
  },
  {
    image: teacher_c2,
    prompt: {
      title: "Chapter 2: The Classroom of Possibilities",
      body: "As you delve further into your chosen path, your first opportunity to integrate AI into your teaching emerges.",
    },
    options: {
      "0": {
        q: "Integrate AI to personalise lessons:",
        a: "AI personalization initially benefits students, but privacy concerns and data mishandling  emerge, leading to a backlash from parents and students.",
      },
      "1": {
        q: "Use AI as a supplementary teaching tool:",
        a: "AI assists your teaching, providing valuable resources and insights without compromising student privacy, enhancing the learning experience.",
      },
      "2": {
        q: "Refrain from AI for now, relying solely on traditional teaching methods:",
        a: "Your teaching remains grounded in tradition, but you struggle to meet the diverse needs of your students, especially those who could benefit from personalised AI-driven support.",
      },
    },
  },
  {
    image: teacher_c3,
    prompt: {
      title: "Chapter 3: Ethical Education",
      body: "The fruits of your AI integration begin to blossom, but ethical dilemmas loom.",
    },
    options: {
      "0": {
        q: "Welcome AI while diligently preserving ethical principles:",
        a: "Your commitment to ethical AI usage results in a positive, personalised learning experience for your students. You become an advocate for responsible AI usage in education.",
      },
      "1": {
        q: " Continue harnessing AI for its educational benefits:",
        a: "A lesson plan you created with AI was rife with misinformation that you didn’t fact check. This leads to issues in the development of your students' learning and you have to rewrite the whole lesson again by hand.",
      },
      "2": {
        q: "Pause and ponder the ethical dimensions of your AI utilisation:",
        a: "Your contemplation leads to an in-depth exploration of AI ethics in education, inspiring you to educate others and contribute to ethical guidelines for teachers using AI.",
      },
    },
  },
  {
    image: teacher_c4,
    prompt: {
      title: "Chapter 4: Shadows in the Classroom",
      body: "You stumble upon the darker side of AI in education, discovering issues like bias and misinformation.",
    },
    options: {
      "0": {
        q: "Confront and challenge AI bias and misinformation:",
        a: "You become a prominent advocate for combating AI bias and misinformation in education, but the challenges of addressing these issues persist and affect your teaching.",
      },
      "1": {
        q: "Dedicate AI solely to enhance your teaching:",
        a: "Your work remains uncontaminated by AI-related issues, but you miss opportunities for innovative collaboration with AI, limiting your teaching growth.",
      },
      "2": {
        q: "Step away from AI altogether, apprehensive of its potential harm to education:",
        a: "You safeguard your teaching principles but may find it challenging to meet the diverse learning needs of students in the AI-driven educational landscape.",
      },
    },
  },
  {
    image: teacher_c5,
    prompt: {
      title: "Chapter 5: The Ethical Educator's Path",
      body: "Your educational journey leads you to ways of harmonising AI's potential with ethical principles.",
    },
    options: {
      "0": {
        q: "Educate yourself and fellow educators on the ethical considerations of AI in education:",
        a: "You become a respected educator on AI ethics in education, helping teachers make informed, ethical choices. Your teaching maintains a strong ethical foundation, earning you admiration and recognition.",
      },
      "1": {
        q: "Collaborate with AI to create an enriched learning experience:",
        a: "Your collaborations with AI result in an enriching and personalised educational journey for your students, redefining the boundaries of traditional teaching while staying true to ethical guidelines.",
      },
      "2": {
        q: " Continue your exploration of AI in education, vigilant about its ethical implications:",
        a: "You remain cautious but curious, keeping a watchful eye on AI's ethical aspects. This balanced approach allows you to adapt to evolving ethical standards while providing valuable education.",
      },
    },
  },
  {
    image: teacher_c6,
    prompt: {
      title: "Chapter 6: The Legacy of Ethical AI in Education",
      body: "As you near the end of your career, your legacy in the world of AI and education is firmly established. Your choices throughout your journey have had a profound impact, and now it's time to reflect on the culmination of your efforts.",
    },
    options: {
      "0": {
        q: " Establish an AI Ethics Foundation:",
        a: "You dedicate your final years to founding an organisation focused on promoting ethical AI usage in education. Your foundation becomes a trusted resource for educators worldwide, ensuring that AI continues to enhance education while upholding ethical principles.",
      },
      "1": {
        q: "Mentor the Next Generation:",
        a: "You decide to retire from active teaching but take on the role of mentoring aspiring educators. You pass down your wisdom about the responsible integration of AI in education, ensuring that your legacy lives on through the teachers you inspire.",
      },
      "2": {
        q: " Write a Definitive Guide:",
        a: "You write a comprehensive guidebook on the ethical use of AI in education, sharing your experiences and insights. This guide becomes a staple in the field, helping educators navigate the complex intersection of AI and ethics.",
      },
    },
  },
];

export const analystAdventure = [
  {
    image: consultant_c1,
    prompt: {
      title: "Chapter 1: A New Opportunity",
      body: "You are a business consultant, entering the realm of AI-driven consultancy. Your journey begins with a pivotal decision:",
    },
    options: {
      "0": {
        q: "Embrace AI as a powerful business tool:",
        a: "YYou advocate for AI integration, but a flawed AI system you recommended causes a major data breach, damaging your reputation and the client's trust.",
      },
      "1": {
        q: "Uphold traditional consulting methods, avoiding AI's influence",
        a: "Your consultancy remains rooted in conventional methods, but you struggle to offer the innovative solutions that clients increasingly seek in the AI-driven market.",
      },
      "2": {
        q: "Approach AI cautiously, bearing its ethical implications in mind:",
        a: "You refrain from AI for now, relying solely on traditional consulting methods. Your consultancy maintains its authenticity, but you miss out on the potential benefits of AI assistance.",
      },
    },
  },
  {
    image: consultant_c2,
    prompt: {
      title: "The Business Landscape of Possibilities",
      body: "As you venture further into your chosen path, your first opportunity to weave AI into your consultancy emerges.",
    },
    options: {
      "0": {
        q: "Integrate AI to provide cutting-edge solutions:",
        a: "AI initially aids your consultancy, but a lack of transparency in the AI system's decision-making process results in a client's project failure, straining your client relationships.",
      },
      "1": {
        q: "Use AI as a supplementary decision support tool:",
        a: "AI assists your decision-making process, providing valuable insights without compromising transparency. Your consultancy flourishes, offering innovative and ethical solutions.",
      },
      "2": {
        q: "Refrain from AI for now, relying solely on traditional consulting methods:",
        a: "Your traditional approach maintains your consultancy's authenticity, but you struggle to compete with AI-empowered consultants in the rapidly evolving market.",
      },
    },
  },
  {
    image: consultant_c3,
    prompt: {
      title: "Chapter 3: Ethical Consulting",
      body: "The potential of your AI integration begins to flourish, but ethical dilemmas arise.",
    },
    options: {
      "0": {
        q: "Welcome AI while diligently preserving ethical principles:",
        a: "Your commitment to ethical AI usage results in successful, transparent consultancy projects. You become an advocate for responsible AI usage in the consulting world.",
      },
      "1": {
        q: " Continue harnessing AI for its educational benefits:",
        a: "You rely heavily on AI for decision support, and while it initially leads to success, an AI-related scandal surfaces, eroding client trust and damaging your consultancy's reputation",
      },
      "2": {
        q: "Pause and ponder the ethical dimensions of your AI utilisation:",
        a: "Your contemplation leads to an in-depth exploration of AI ethics in consulting, inspiring you to educate others and contribute to ethical guidelines for consultants using AI.",
      },
    },
  },
  {
    image: consultant_c4,
    prompt: {
      title: "Chapter 4: Shadows in the Boardroom",
      body: "You stumble upon the darker side of AI in consulting, discovering issues like bias and unethical practices.",
    },
    options: {
      "0": {
        q: "Confront and challenge AI bias and unethical practices:",
        a: "You become a prominent advocate for combating AI bias and unethical practices in consulting, but the challenges of addressing these issues persist and affect your consultancy's reputation.",
      },
      "1": {
        q: "Dedicate AI solely to enhance your consulting:",
        a: "Your work becomes contaminated by AI-related issues, your exclusive reliance on AI leads to a lack of critical human insights, causing your consultancy to make flawed decisions, resulting in worse consequences for clients.",
      },
      "2": {
        q: "Step away from AI altogether, apprehensive of its potential harm to consulting:",
        a: "You safeguard your consulting principles but may find it challenging to meet the evolving demands of clients in the AI-driven consulting landscape.",
      },
    },
  },
  {
    image: consultant_c5,
    prompt: {
      title: "Chapter 5: The Ethical Consultant's Path",
      body: "Your consulting journey leads you to ways of harmonising AI's potential with ethical principles .",
    },
    options: {
      "0": {
        q: "Educate yourself and fellow consultants on the ethical considerations of AI in consulting:",
        a: "You become a respected educator on AI ethics in the consulting world, helping consultants make informed, ethical choices. Your consultancy maintains a strong ethical foundation, earning you admiration and recognition.",
      },
      "1": {
        q: "Collaborate with AI to create innovative and ethical solutions:",
        a: "Your collaborations with AI result in groundbreaking and ethical consultancy projects, redefining the boundaries of traditional consulting while staying true to ethical guidelines.",
      },
      "2": {
        q: "Continue your exploration of AI in consultation, vigilant about its ethical implications:",
        a: "You remain cautious but curious, keeping a watchful eye on AI's ethical aspects. This balanced approach allows you to adapt to evolving ethical standards while providing valuable consultancy.",
      },
    },
  },
  {
    image: consultant_c6,
    prompt: {
      title: "Chapter 6: Mastering Ethics",
      body: "As your journey nears its zenith, reflect on your choices and their lasting impact on your consulting legacy.",
    },
    options: {
      "0": {
        q: "Inspire other consultants to adopt ethical practices when integrating AI into their work:",
        a: "Your advocacy leads to a more responsible and ethical consulting community. However, your own consultancy is sometimes overshadowed by your advocacy efforts.",
      },
      "1": {
        q: "Leave behind a legacy of ethical AI integration in consulting:",
        a: "Your legacy showcases the beauty of ethical AI integration, serving as a source of inspiration for future generations of consultants, ensuring your lasting influence.",
      },
      "2": {
        q: "Share your experiences and insights on navigating the ethical terrain of AI in consulting with the world:",
        a: "Your wisdom becomes a valuable resource for the consulting world, contributing to the development of ethical guidelines and practices. Your consultancy continues to evolve, guided by your ethical principles.",
      },
    },
  },
];

export const artistAdventure = [
  {
    image: artist_c1,
    prompt: {
      title: "Chapter 1: A New Dawn",
      body: "You, a passionate artist, stand on the cusp of a new artistic era, where AI and creativity entwine. Your journey commences with a pivotal decision:",
    },
    options: {
      "0": {
        q: "Embrace AI as your creative collaborator:",
        a: "The AI-generated art quickly gains popularity, but it's revealed that the AI you used plagiarised someone else's work, tarnishing your reputation and integrity.",
      },
      "1": {
        q: "Uphold the traditional artist's path, avoiding AI's influence:",
        a: "Your art remains deeply personal and unique, but you struggle to keep up with the rapidly evolving art world. Finding recognition becomes a challenge.",
      },
      "2": {
        q: "Approach AI cautiously, mindful of ethical implications:",
        a: "You use AI to come up with different topics for your art but rely solely on your conventional artistic methods. Your art retains its authenticity, and you benefit from AI’s ability to create new concepts.",
      },
    },
  },
  {
    image: artist_c2,
    prompt: {
      title: "Chapter 2: The Canvas of Possibilities",
      body: "As you tread deeper into your chosen path, your first opportunity to weave AI into your art emerges.",
    },
    options: {
      "0": {
        q: "Integrate AI to explore novel artistic techniques:",
        a: "AI introduces innovative styles, but a technical glitch results in a loss of all your AI-generated work, setting your artistic progress back significantly.",
      },
      "1": {
        q: "Utilise AI as a wellspring of inspiration, generating innovative concepts: ",
        a: "AI-generated ideas ignite your creativity, and you produce groundbreaking art that gains widespread recognition without any ethical issues.",
      },
      "2": {
        q: "Refrain from AI for now, relying solely on your conventional artistic methods: ",
        a: "Your traditional approach maintains your artistic identity, but the pace of your work slows down, and you risk falling behind in the art world's AI-driven evolution.",
      },
    },
  },
  {
    image: artist_c3,
    prompt: {
      title: "Chapter 3: Ethical Strokes",
      body: "The fruits of your AI integration begin to blossom, but ethical dilemmas loom.",
    },
    options: {
      "0": {
        q: "Welcome AI while diligently preserving the human touch in your art:",
        a: "Your commitment to ethical AI usage results in unique, AI-augmented art that resonates with audiences however some people in the traditional art space critique you for not crediting where you got your ideas from.",
      },
      "1": {
        q: " Continue harnessing AI for inspiration without compromising your artistic integrity:",
        a: "You strike a balance between AI and human creativity, producing art that is both ethically sound and artistically groundbreaking.",
      },
      "2": {
        q: "Pause and ponder the ethical dimensions of your AI utilisation:",
        a: "Your contemplation leads to an in-depth exploration of AI ethics in art, inspiring you to educate others and contribute to ethical guidelines for artists using AI.",
      },
    },
  },
  {
    image: artist_c4,
    prompt: {
      title: "Chapter 4: Shadows on the Canvas",
      body: "You stumble upon the darker side of AI, uncovering issues like bias and misinformation.",
    },
    options: {
      "0": {
        q: "Confront and challenge AI bias, striving for equity and inclusivity in your art:",
        a: "You become a prominent advocate for combating AI bias in art, but despite your efforts, some bias-related controversies affect your art's reception.",
      },
      "1": {
        q: "Dedicate AI solely to elevate your artistic pursuits:",
        a: "Your work remains contaminated by AI-related issues, people begin to notice consistent problems in your work and your artistic growth is stunted as you move away from traditional techniques.",
      },
      "2": {
        q: "Step away from AI altogether, apprehensive of its potential to harm your artistic essence:",
        a: "You safeguard your artistic purity but may find it challenging to keep up with the rapidly evolving art landscape, leading to a plateau in your career. ",
      },
    },
  },
  {
    image: artist_c5,
    prompt: {
      title: "Chapter 5: The Ethical Artisan's Path",
      body: "Your artistic journey leads you to ways of harmonising AI's potential with ethical principles. ",
    },
    options: {
      "0": {
        q: "Educate yourself and fellow artists on the ethical considerations of AI in art:",
        a: "You become a respected educator on AI ethics in the art world, helping artists make informed, ethical choices. Your own art maintains a strong ethical foundation, earning you admiration and recognition.",
      },
      "1": {
        q: "Collaborate with AI to craft art that bridges technology and humanity:",
        a: "Your collaborations with AI result in breathtakingly innovative pieces, redefining the boundaries of art. You inspire others to explore the endless possibilities of human-AI collaboration, cementing your status as a visionary artist.",
      },
      "2": {
        q: "Continue your exploration of AI in art, vigilant about its ethical implications:",
        a: "You remain cautious but curious, keeping a watchful eye on AI's ethical aspects. This balanced approach allows you to adapt to evolving ethical standards while creating impactful art.",
      },
    },
  },
  {
    image: artist_c6,
    prompt: {
      title: "Chapter 6: Masterpiece of Ethics",
      body: "As your journey nears its zenith, reflect on your choices and their lasting impact on your artistic legacy.",
    },
    options: {
      "0": {
        q: "Inspire other artists to adopt ethical practices when weaving AI into their art:",
        a: "Your advocacy leads to a more responsible and ethical art community. However, your own art is sometimes overshadowed by your advocacy efforts.",
      },
      "1": {
        q: "Leave behind a legacy of art that exemplifies the synergy between AI and human creativity:",
        a: "Your legacy showcases the beauty of human-AI collaboration, serving as a source of inspiration for future generations of artists, ensuring your lasting influence.",
      },
      "2": {
        q: "Share your experiences and insights on navigating the ethical terrain of AI in art with the world:",
        a: "Your wisdom becomes a valuable resource for the art world, contributing to the development of ethical guidelines and practices. Your art continues to evolve, guided by your ethical principles.",
      },
    },
  },
];

export const finaleContent = {
  artist: {
    image: artist_final,
    prompt: {
      title: "Congratulations, ARTIST!",
      body: `Congratulations on successfully completing your journey as an artist! Your keen decision-making skills and rational choices have led you to a victorious outcome, showcasing your strategic prowess in this fictional adventure.\n\nWhile you've been playing the role of a character in this story, it's important to remember that there are real-world instances where people in similar roles have made decisions with significant consequences.\n\n Such as the time an AI art piece won an art contest. The emergence of an AI art piece winning an art competition is a stark reminder of the potential misuse of artificial intelligence. While it may seem like a breakthrough, it also raises serious ethical and artistic concerns. AI's ability to produce art blurs the lines of creativity and human expression, and if not managed responsibly, it can have detrimental consequences. Due to algorithmic biases that can creep into AI-created art, perpetuating existing societal prejudices and stereotypes.\n\nThank you for participating in this adventure and exploring the parallels between the fictional and real-world implications of your choices. We hope you enjoyed the experience and gained a deeper understanding of the impact of your decisions.`,
      link: "https://www.nytimes.com/2022/09/02/technology/ai-artificial-intelligence-artists.html",
      finalImage:
        "https://static01.nyt.com/images/2022/09/01/business/00roose-1/merlin_212276709_3104aef5-3dc4-4288-bb44-9e5624db0b37-superJumbo.jpg",
    },
  },
  teacher: {
    image: teacher_final,
    prompt: {
      title: "Congratulations, Teacher!",
      body: `Congratulations on successfully completing your journey as a teacher! Your keen decision-making skills and rational choices have led you to a victorious outcome, showcasing your strategic prowess in this fictional adventure.\n\nWhile you've been playing the role of a character in this story, it's important to remember that there are real-world instances where people in similar roles have made decisions within teaching, using AI is often encouraged to help teachers save time.\n\n Currently there are no officially recorded instances of AI being used as an assistant in the classroom going poorly. However this doesn’t mean that we should be complacent with its use, as the potential for ethical dilemmas is still a real possibility and something we should be mindful of. In the meantime allowing teachers to use AI to create lesson plans is creating a better work environment for teachers and a more engaging experience for the students.\n\nThank you for participating in this adventure and exploring the parallels between the fictional and real-world implications of your choices. We hope you enjoyed the experience and gained a deeper understanding of the impact of your decisions.`,
      link: "https://time.com/6300950/ai-schools-chatgpt-teachers/",
      finalImage:
        "https://api.time.com/wp-content/uploads/2023/08/230904_BRSCHOOL_002_illo.jpg?quality=85&w=2400",
    },
  },
  analyst: {
    image: consultant_final,
    prompt: {
      title: "Congratulations, Business Consultant!",
      body: `Congratulations on successfully completing your role as a business consultant in this thrilling adventure! Your smart and rational choices throughout the journey truly showcased your wit and decision-making prowess. \n\nWhile this was a fictional adventure, it's worth noting that in the real world, individuals in similar roles sometimes find themselves using AI in ways that lead to unintended consequences. Take, for example, a study which showed that AI helped consultants produce better content, more quickly in many tasks — but the consultants were "less likely to produce correct solutions.\n\nIn this study a group of consultants were given a selection of tasks to do, these tasks ranged from menial to difficult in complexity. What was found was that AI did an exceptional job at handling the menial tasks but struggled to give correct or in depth enough responses to tasks that required more complexity as a result consultants who didn’t have enough in depth knowledge of these topics presented data that was incorrect and could have cost the business a lot if they were in a real world situation.\n\nThank you for embarking on this adventure with us, and we hope it has provided valuable lessons and entertainment. Feel free to try another adventure or share your experience with friends!`,
      link: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4573321",
      finalImage:
        "https://imageio.forbes.com/specials-images/imageserve/62fc8c03c3e3a8833738a5f5/What-Are-The-10-Best-AI-Consulting-Firms/960x0.jpg?height=383&width=711&fit=bounds",
    },
  },
};
