import SectionWrapper from "src/hoc/SectionWrapper";
import React from "react";

const PrepromptChat = () => {
  return (
    <div className="max-w-4xl mx-auto p-4">
      <div className="mb-8">
        <h2 className="text-2xl font-semibold mb-2">Machine Learning Bias</h2>
        <p>
          Machine learning bias, also known as algorithm bias or AI bias, is a
          phenomenon that occurs when an algorithm produces results that are
          systemically prejudiced due to erroneous assumptions in the machine
          learning (ML) process. This bias is detrimental because it
          discriminates against specific groups, has a negative impact on
          society, and undermines trust in AI.
        </p>
      </div>
      <div>
        <h2 className="text-2xl font-semibold mb-2">Sources of Bias</h2>
        <p>
          Bias can get into AI in two ways: via the data and the algorithm
          itself. Models can be trained on data that encapsulates human
          decisions or that reflects secondary consequences of societal or
          historical inequities. Additionally, data generated by users can
          create feedback loops that perpetuate bias. On the other hand, machine
          learning algorithms may identify statistical correlations that are
          socially unacceptable or even illegal.
        </p>
      </div>
    </div>
  );
};

export default PrepromptChat;
